//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.28 at 11:26:15 AM MSK 
//


package ru.kogut.soapclient.products.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the products.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetAllProductsResponse_QNAME = new QName("http://kogut.ru/ws/products", "getAllProductsResponse");
    private final static QName _GetProductResponse_QNAME = new QName("http://kogut.ru/ws/products", "getProductResponse");
    private final static QName _GetAnswerResponse_QNAME = new QName("http://kogut.ru/ws/products", "GetAnswerResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: products.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SaveProductRequest }
     * 
     */
    public SaveProductRequest createSaveProductRequest() {
        return new SaveProductRequest();
    }

    /**
     * Create an instance of {@link UpdateProductRequest }
     * 
     */
    public UpdateProductRequest createUpdateProductRequest() {
        return new UpdateProductRequest();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link GetProductByIdRequest }
     * 
     */
    public GetProductByIdRequest createGetProductByIdRequest() {
        return new GetProductByIdRequest();
    }

    /**
     * Create an instance of {@link DeleteProductRequest }
     * 
     */
    public DeleteProductRequest createDeleteProductRequest() {
        return new DeleteProductRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kogut.ru/ws/products", name = "getAllProductsResponse")
    public JAXBElement<Object> createGetAllProductsResponse(Object value) {
        return new JAXBElement<Object>(_GetAllProductsResponse_QNAME, Object.class, null, value);
    }

    @XmlElementDecl(namespace = "http://kogut.ru/ws/products", name = "getProductResponse")
    public JAXBElement<Object> createProductResponse(Object value) {
        return new JAXBElement<Object>(_GetProductResponse_QNAME, Object.class, null, value);
    }

    @XmlElementDecl(namespace = "http://kogut.ru/ws/products", name = "GetAnswerResponse")
    public JAXBElement<GetAnswerResponse> createGetAnswerResponse(GetAnswerResponse value) {
        return new JAXBElement<GetAnswerResponse>(_GetAnswerResponse_QNAME, GetAnswerResponse.class, null, value);
    }

}
