//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.28 at 10:51:02 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://kogut.ru/ws/clients", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.kogut.soapclient.clients.wsdl;
